export enum UserAuthority {
  USER_ADMINISTRATION_READ = 'USER_ADMINISTRATION:read',
  USER_ADMINISTRATION_WRITE = 'USER_ADMINISTRATION:write',
  AUTHORITY_ADMINISTRATION_READ = 'AUTHORITY_ADMINISTRATION:read',
  AUTHORITY_ADMINISTRATION_WRITE = 'AUTHORITY_ADMINISTRATION:write',
  ROLE_ADMINISTRATION_READ = 'ROLE_ADMINISTRATION:read',
  ROLE_ADMINISTRATION_WRITE = 'ROLE_ADMINISTRATION:write',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
}
